// ***********************************************************************
// <author>Stephan B</author>
// <copyright company="Comindware">
//   Copyright (c) Comindware 2010-2013. All rights reserved.
// </copyright>
// <summary>
//   TreeNodeVisitor.cs
// </summary>
// ***********************************************************************

using JetBrains.Annotations;
using JetBrains.ReSharper.Psi.Tree;

namespace JetBrains.ReSharper.Psi.Secret.Tree
{
    /*/// <summary>TODO: replace it with the one generated by parserGen.</summary>
    public abstract partial class TreeNodeVisitor
    {
        public virtual void VisitNode([NotNull] ITreeNode node)
        {
        }
    }

    /// <summary>TODO: replace it with the one generated by parserGen.</summary>
    public abstract partial class TreeNodeVisitor<TContext>
    {
        public virtual void VisitNode([NotNull] ITreeNode node, TContext context)
        {
        }
    }

    /// <summary>TODO: replace it with the one generated by parserGen.</summary>
    public abstract partial class TreeNodeVisitor<TContext, TReturn>
    {
        public virtual TReturn VisitNode([NotNull] ITreeNode node, TContext context)
        {
            return default(TReturn);
        }
    }*/
}
